# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RnLn7mLepWHuB3yaYOLIWQ2bjYQDxck8
"""

!pip install kaggle

from google.colab import files
import pandas as pd

# Kaggle API ni yuklash
!pip install kaggle

# Kaggle API ni aktivatsiya qilish
from google.colab import files
files.upload()

# Kaggle API ni aktivatsiya qilish
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Datasetni yuklash
!kaggle datasets download -d username/dataset-name

# Datasetni o'qiyotirish va pandas DataFrame sifatida o'rnatish
data = pd.read_csv('dataset-name.csv')
print(data.head())

import kagglehub

# Download latest version
path = kagglehub.dataset_download("steve1215rogg/student-lifestyle-dataset")

print("Path to dataset files:", path)